export const skillsList = [
    "C",
    "C++",
    "Java",
    "HTML/CSS",
    "Javascript",
    "React.Js",
    "Next.js",
    "TypeScript",
    "Node.js",
    "Express", 
    "Flask",
    "FastAPI",
    "python",
    "TailwindCSS",
    "MaterialUI",
    "Bootstrap",
    "Lexx/Yacc",
    "Git",
    "Perl",

];